----------------------------------------------------------------------
---------- Nuevas Tablas y/o Vistas 
----------------------------------------------------------------------

CREATE OR REPLACE VIEW PP_OM AS
SELECT om.ad_client_id, om.ad_org_id, om.isactive, om.created, om.createdby, om.updated, om.updatedby, om.m_product_id, prod.value AS codprod, prod.name AS nameprod, om.pp_product_bom_id, om.m_warehouse_id, om.ad_workflow_id, om.qtyentered, om.qtydelivered, om.dateordered, om.datepromised, om.datestart, om.datestartschedule, om.datefinish, om.datefinishschedule, om.docstatus, om.m_attributesetinstance_id, bom.name AS nameprodbom, wh.name AS namewarehouse, wf.name AS nameworkflow, attr.description AS nameattr, om.pp_order_id, om.pp_order_id AS pp_om_id FROM (((((pp_order om LEFT JOIN m_product prod ON ((prod.m_product_id = om.m_product_id))) LEFT JOIN ad_workflow wf ON ((wf.ad_workflow_id = om.ad_workflow_id))) LEFT JOIN m_warehouse wh ON ((wh.m_warehouse_id = om.m_warehouse_id))) LEFT JOIN pp_product_bom bom ON ((bom.pp_product_bom_id = om.pp_product_bom_id))) LEFT JOIN m_attributesetinstance attr ON ((attr.m_attributesetinstance_id = om.m_attributesetinstance_id))) WHERE (om.isactive = 'Y'::bpchar);

CREATE OR REPLACE VIEW PP_OM_BOM AS
SELECT ombomline.ad_client_id, ombomline.ad_org_id, ombomline.isactive, ombomline.created, ombomline.createdby, ombomline.updated, ombomline.updatedby, ombomline.m_product_id, prod.value AS codprod, prod.name AS nameprod, ombomline.qtybom, ombomline.qtyentered, ombomline.qtyreserved, ombomline.iscritical, ombomline.isqtypercentage, ombom.pp_order_bom_id, ombom.pp_order_id, ombom.pp_order_id AS pp_om_id FROM ((pp_order_bomline ombomline LEFT JOIN pp_order_bom ombom ON ((ombom.pp_order_bom_id = ombomline.pp_order_bom_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = ombomline.m_product_id)));

CREATE OR REPLACE VIEW PP_OM_WF AS
SELECT omnode.ad_client_id, omnode.ad_org_id, omnode.isactive, omnode.created, omnode.createdby, omnode.updated, omnode.updatedby, omnode.value, omnode.name, omnode.qtyrequired, omnode.durationrequired, omnode.durationreal, omwf.pp_order_id, omnode.datestart, omnode.datestartschedule, omnode.datefinish, omnode.datefinishschedule, res.name AS nameresource, res.value AS valueresource, omwf.pp_order_id AS pp_om_id FROM ((pp_order_node omnode LEFT JOIN pp_order_workflow omwf ON ((omwf.pp_order_workflow_id = omnode.pp_order_workflow_id))) LEFT JOIN s_resource res ON ((res.s_resource_id = omnode.s_resource_id)));

----------------------------------------------------------------------
---------- Nuevas columnas en tablas y/o vistas 
----------------------------------------------------------------------

CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_ReqInfo AS
SELECT reqlines.ad_client_id, reqlines.ad_org_id, reqlines.isactive, reqlines.created, reqlines.createdby, reqlines.updated, reqlines.updatedby, reqlines.qty, req.daterequired, req.datedoc, req.docstatus, prod.m_product_id, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prov.c_bpartner_id, prov.value AS codprov, prov.name AS nameprov, req.documentno FROM ((((m_requisitionline reqlines LEFT JOIN m_requisition req ON ((req.m_requisition_id = reqlines.m_requisition_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = reqlines.c_uom_id))) LEFT JOIN c_bpartner prov ON ((prov.c_bpartner_id = reqlines.c_bpartner_id))) LEFT JOIN m_product prod ON ((prod.m_product_id = reqlines.m_product_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prov.isactive = 'Y'::bpchar));
CREATE OR REPLACE VIEW PP_Prod_BOMLine AS
SELECT prod_bomline.pp_product_bom_id, prod_bomline.isqtypercentage, prod_bomline.qtybom, prod_bomline.scrap, prod_bomline.qtybatch, prod_bomline.componenttype, prod.value AS codprod, prod.name AS nameprod, uom.name, uom.uomsymbol, prod_bomline.ad_client_id, prod_bomline.ad_org_id, prod_bomline.isactive, prod_bomline.created, prod_bomline.createdby, prod_bomline.updated, prod_bomline.updatedby, prod_bomline.pp_product_bomline_id, prod.ispurchased FROM ((pp_product_bomline prod_bomline LEFT JOIN m_product prod ON ((prod.m_product_id = prod_bomline.m_product_id))) LEFT JOIN c_uom uom ON ((uom.c_uom_id = prod_bomline.c_uom_id))) WHERE ((prod.isactive = 'Y'::bpchar) AND (prod_bomline.isactive = 'Y'::bpchar));
----------------------------------------------------------------------
---------- Modificación de tablas y/o vistas
----------------------------------------------------------------------

